---
title: "Interactive Maps of Submarine Cable Analysis for US Marine Renewable Energy Development"
output:
  bookdown::html_document2:
    number_sections: yes
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=F)

# set working directory
if (basename(getwd()) == 'nrel-cables') setwd('docs')

# load packages and variables
source('./packages_vars.R')

#opts_chunk$set(warning=F, message=F)
opts_chunk$set(warning=F, message=F, eval=T, cache=T) # DEBUG
fig_type = 'png' # 'png','pdf','html'
fig_dpi = 300
redo = F

if (interactive() || "rmarkdown.pandoc.to" %in% names(opts_knit$get()) && opts_knit$get("rmarkdown.pandoc.to") == 'html'){
  out_html = T
  #opts_chunk$set(echo=T)
  opts_chunk$set(echo=F)
} else {
  out_html = F
  opts_chunk$set(echo=F)
}

map_energy_sf = function(
  energy_sf,
  ter,
  legend_title){
  # ter = 'Hawaii'; energy_sf = wind_sf; legend_title = 'Wind\nspeed\n(m/s)'; redo = T
  
  d = energy_sf %>% 
    filter(territory==ter)
  cables = lns_d1x %>%
    filter(territory==ter)
  cables2 = cbls2 %>%
    filter(territory==ter)
  cables3 = cbls3  %>%
    filter(territory==ter)

  bb = st_bbox(d)

  pal_energy = colorFactor('BuGn',      d$energy)
  pal_depth  = colorFactor('OrRd', cables3$depth, reverse=T)
  
  m = leaflet(d) %>% 
    addProviderTiles('Stamen.TonerLite', group = 'B&W') %>%
    addProviderTiles('Esri.OceanBasemap', group = 'Ocean') %>%
    addPolygons(
      group=legend_title,
      fillColor = ~pal_energy(energy), fillOpacity = 0.5, color=NA) %>% 
    addPolygons(
      data = cables2, group='Min. Cable (2x)',
      fillColor=~pal_depth(depth), fillOpacity = 0.3, color=NA) %>%
    addPolygons(
      data = cables3, group='Rec. Cable (3x)',
      fillColor=~pal_depth(depth), fillOpacity = 0.3, color=NA) %>%      
    addPolylines(
      data = cables, group='Cables',
      color='black', opacity = 0.5, weight=0.4) %>% #,
    fitBounds(bb[['xmin']],bb[['ymin']],bb[['xmax']],bb[['ymax']]) %>%
    addLegend(
      position='bottomright', 
      pal=pal_energy, values=~energy, title=legend_title) %>%
    addLegend(
      position='bottomright', 
      pal=pal_depth, values=cables3$depth, title='Cable Depth') %>%
    addLayersControl(
      baseGroups = c('Ocean','B&W'),
      overlayGroups = c(legend_title, 'Min. Cable (2x)', 'Rec. Cable (3x)', 'Cables'),
      options = layersControlOptions(collapsed=T))
   m
}

map_tide = function(
  ter,
  legend_title='Tidal\npower\n(W/m2)'){
  # ter = 'Puerto Rico'; legend_title = 'Tidal\npower\n(W/m2)'
  # ter = 'Alaska'; legend_title = 'Tidal\npower\n(W/m2)'
  
  ter_str = str_replace_all(ter, ' ', '-')
  tif = sprintf('../data/tide_ter-%s.tif', ter_str)
  r = raster(tif) # plot(r)
  
  # aggregate and adjust to [-180,180] from [0,360] for leaflet to show
  r_a = aggregate(r, fact=8, fun=max) %>%
    shift(-360) %>%
    cut(breaks = tide_breaks, include.lowest=T)
  bb = bbox(r_a)
  
  # use cables reprojected to [-180,180]
  cables = cbls_180 %>%
    filter(territory==ter)
  cables2 = cbls2_180 %>%
    filter(territory==ter)
  cables3 = cbls3_180 %>%
    filter(territory==ter)

  n_lbl = length(tide_labels)
  pal_energy = colorFactor(
    palette = 'BuGn', na.color="#00000000",
    domain  = 1:n_lbl)
  pal_depth  = colorFactor('OrRd', cables3$depth, reverse=T)

  m = leaflet() %>% 
    addProviderTiles('Stamen.TonerLite', group = 'B&W') %>%
    addProviderTiles('Esri.OceanBasemap', group = 'Ocean') %>%
    addRasterImage(
      r_a, group=legend_title,
      colors=pal_energy, opacity=0.7) %>%
    addPolygons(
      data = cables3, group='Min. Cable (2x)',
      fillColor=~pal_depth(depth), fillOpacity = 0.3, color=NA) %>%
    addPolygons(
      data = cables2, group='Rec. Cable (3x)',
      fillColor=~pal_depth(depth), fillOpacity = 0.3, color=NA) %>%      
    addPolylines(
      data = cables, group='Cables',
      color='black', opacity = 0.5, weight=0.4) %>%
    fitBounds(bb[1,'min'],bb[2,'min'],bb[1,'max'],bb[2,'max']) %>%
    addLegend(
      position = 'bottomright', 
      colors   = pal_energy(1:n_lbl), 
      labels   = tide_labels,
      title=legend_title) %>%
    addLegend(
      position='bottomright', 
      pal=pal_depth, values=cables3$depth, title='Cable Depth') %>%
    addLayersControl(
      baseGroups = c('Ocean','B&W'),
      overlayGroups = c(legend_title, 'Min. Cable (2x)', 'Rec. Cable (3x)', 'Cables'),
      options = layersControlOptions(collapsed=T))
   m
}

# calculate length of cables / comment to speed up
# lns_km = read_sf(lns_geo) %>%
#   mutate(
#     length = st_length(geometry)) %>%
#   summarize(length_km = sum(length)/1000) %>% 
#   .$length_km %>% as.numeric()
# 
# lns_d1x_km = lns_d1x %>%
#   mutate(
#     length = st_length(geometry)) %>%
#   summarize(length_km = sum(length)/1000) %>% 
#   .$length_km %>% as.numeric()
lns_km = 230834.9
lns_d1x_km = 97321.2

# revert to old red-green-blue default color, not new viridis
#   per https://github.com/tidyverse/ggplot2/blob/00ecd3670ef0f1c195bf4c6b5ada3b1895712f1c/NEWS.md#ggplot2-2219000
scale_fill_ordinal = scale_fill_hue

#usa2    = wrld2 %>% filter(ID=='USA')
wrld2   = st_as_sf(map('world2', plot=F, fill=T))
usa_eez = read_sf(usa_rgn_geo)
land    = read_sf(land_usaeez_geo)
lns_d1x = read_sf(lns_d1x_rgn_geo)
dx2     = read_sf(dx2_depth_geo)
dx3     = read_sf(dx3_depth_geo)
usa_dx = read_csv(usa_dx_csv)

cbls2 = dx2 %>%
  mutate(
    depth = factor(
      x      = depth_factor,
      levels = depth_labels,
      labels = depth_labels,
      ordered = T))
cbls3 = dx3  %>%
  mutate(
    depth = factor(
      x      = depth_factor,
      levels = depth_labels,
      labels = depth_labels,
      ordered = T))

# set to [-180,180] from [0,360] for tide raster leaflet -- hacked at:
#  [sf::st_transform not honoring +lon_wrap](https://github.com/edzer/sfr/issues/280)
cbls_180 = lns_d1x %>%
    mutate(geometry = (geometry + c(360,90)) %% c(-360) - c(0,-360+90)) %>% 
    st_set_crs(crs_gcs)
cbls2_180 = cbls2 %>%
    mutate(geometry = (geometry + c(360,90)) %% c(-360) - c(0,-360+90)) %>% 
    st_set_crs(crs_gcs)
cbls3_180 = cbls3  %>%
    mutate(geometry = (geometry + c(360,90)) %% c(-360) - c(0,-360+90)) %>% 
    st_set_crs(crs_gcs)
```

# Tide

## Alaska

```{r}
map_tide('Alaska')
```

## East

```{r}
map_tide('East')
```

## Gulf of Mexico

```{r}
map_tide('Gulf of Mexico')
```

## Puerto Rico

```{r}
map_tide('Puerto Rico')
```

## US Virgin Islands

```{r}
map_tide('US Virgin Islands')
```

## West

```{r}
map_tide('West')
```

# Wind

```{r mapWind_data}
wind_sf = read_sf(wind_geo) %>%
    filter(!is.na(territory)) %>%
    mutate(
      energy = factor(
        x      = energy_lbl,
        levels = wind_labels,
        labels = wind_labels,
        ordered = T)) %>%
    select(-energy_num, -energy_lbl, -region) %>%
    arrange(territory, energy)
```

## East

```{r}
map_energy_sf(wind_sf, 'East', 'Wind\nspeed\n(m/s)')
```

## Gulf of Mexico

```{r}
map_energy_sf(wind_sf, 'Gulf of Mexico', 'Wind\nspeed\n(m/s)')
```

## Hawaii

```{r}
map_energy_sf(wind_sf, 'Hawaii', 'Wind\nspeed\n(m/s)')
```

## West

```{r}
map_energy_sf(wind_sf, 'West', 'Wind\nspeed\n(m/s)')
```

# Wave

```{r mapWave_data}
wave_sf = read_sf(wave_geo) %>%
  filter(!is.na(territory)) %>%
  mutate(
    energy = factor(
      x      = energy_lbl,
      levels = wave_labels,
      labels = wave_labels,
      ordered = T)) %>%
  select(-energy_num, -energy_lbl) %>%
  arrange(territory, energy)
```

## Alaska

```{r}
map_energy_sf(wave_sf, 'Alaska', 'Wave\nenergy\n(kW/m)')
```

## East

```{r}
map_energy_sf(wave_sf, 'East', 'Wave\nenergy\n(kW/m)')
```

## Gulf of Mexico

```{r}
map_energy_sf(wave_sf, 'Gulf of Mexico', 'Wave\nenergy\n(kW/m)')
```

## Hawaii

```{r}
map_energy_sf(wave_sf, 'Hawaii', 'Wave\nenergy\n(kW/m)')
```

## Puerto Rico

```{r}
map_energy_sf(wave_sf, 'Puerto Rico', 'Wave\nenergy\n(kW/m)')
```

## US Virgin Islands

```{r}
map_energy_sf(wave_sf, 'US Virgin Islands', 'Wave\nenergy\n(kW/m)')
```

## West

```{r}
map_energy_sf(wave_sf, 'West', 'Wave\nenergy\n(kW/m)')
```


```{r mapTide leaflet, eval=F}
## Tidal
#tide = raster(tide_tif)
#plot(tide_tif)
# TODO: in report.Rmd, leaflet viz tide rasters per territory w/ regex in data/tide_ter-*.tif

territories = read_csv(tide_cbls_csv) %>% 
  filter(territory !='ALL') %>% 
  .$territory %>% unique()
```
